default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: root
  password:
  reconnect: true

development:
  <<: *default
  host: localhost
  database: bracket_development

test:
  <<: *default
  host: localhost
  database: bracket_test

production: &production
  <<: *default
  database: <%= Rails.application.credentials.db.try(:[], :database) || 'x' %>
  host: <%= Rails.application.credentials.db.try(:[], :host) || 'x' %>
  username: <%= Rails.application.credentials.db.try(:[], :username) || 'x' %>
  password: <%= Rails.application.credentials.db.try(:[], :password) || 'x' %>
